baseURL = 'https://conference.nbody.shop/'
languageCode = 'en-us'
title = 'N-Body Shop Excellence Conference 2025'
#theme = 'ananke'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
